### PR TITLE
DO NOT MERGE

### LINKED ISSUE #5: Search Functionality for Blogs and Learnings
**Is your feature request related to a problem? Please describe.**
As content in the "Blogs" and "Learnings" sections grows, it becomes difficult to quickly find specific articles or topics without a dedicated search feature.

**Describe the solution you'd like**
Implement a search bar that allows users to search across both "Blogs" and "Learnings" sections using keywords, titles, or tags. This would improve content discoverability and save users time when looking for specific information.

**Describe alternatives you've considered**
Manually browsing through content is an option, but it’s time-consuming and not practical for large collections of posts.

**Additional context**
A search feature would make the portfolio template more scalable and user-friendly as more content is added.

### PR DESCRIPTION
**Pull request by yaralahruthik**
Raising a quick PR to check the deployment of this feature.

### CODE REVIEW

**Comment by yaralahruthik** [comment]
Hmm, @NitanJana any idea why this is failing 
image

Something to do with the conditional check?

**Comment by NitanJana** [comment]
@yaralahruthik I'm not sure why these assets are not loading, maybe because we're loading them outside head?
image

**Comment by NitanJana** [comment]
image

try once while genereting the pagefind dir without output-path option.

**Comment by NitanJana** [comment]
Check this https://magical-daffodil-c93181.netlify.app/
This is after fixing the build script.
But the search bar flickers on changing route.

**Comment by yaralahruthik** [comment]
> Check this https://magical-daffodil-c93181.netlify.app/
> This is after fixing the build script.

There is actually an astro integration called `astro-pagefind`, I tried that earlier and it was working great!

Can we reverse engineer that integration to understand the best way to do it here?

I don't want to use that integration as there are some limitations in terms of features.

**Comment by NitanJana** [comment]
Sure, I'll study the package tomorrow.

**Comment by yaralahruthik** [comment]
@NitanJana I feel like this feature can be hold off for now. Can be added if someone requests for this feature. At the moment, this is not aligning with the website structure.

**Pull request closed without merging**
