### PR TITLE
Fixes #9: Prevent Ai bots from crawling the website

### LINKED ISSUE #9: Prevent AI Bots from Crawling the Website
**Is your feature request related to a problem? Please describe.**  
It's frustrating when AI bots or web scrapers crawl the website, potentially consuming resources, collecting sensitive information, or affecting website performance without permission. This can lead to privacy concerns and increased server load, which degrades the user experience.

**Describe the solution you'd like**  
I would like the website to include measures that prevent AI bots and other unauthorized crawlers from accessing and indexing the site. This can be done by implementing the `robots.txt` file to disallow specific user agents or by incorporating CAPTCHA for suspicious traffic. Additionally, adding security headers or bot-detection software can help mitigate unwanted bot activity.

**Describe alternatives you've considered**  
An alternative approach could be to allow certain trusted bots while blocking others. For example, allowing only search engine bots like Google or Bing but blocking the rest. Another option would be to monitor traffic patterns and block bots based on behavior or IP.

**Additional context**  
Adding a well-configured `robots.txt` file could be a quick win, while CAPTCHA or bot-detection software would provide an extra layer of protection. It’s important to monitor the effectiveness of this solution and adjust settings as new bot technologies emerge. Hosting provider-specific guidance can also be added.

### PR DESCRIPTION
**Pull request by NitanJana**
### Summary
This pull request addresses issue #9 by implementing measures to prevent AI bots from crawling the website.

### Changes Made
- Added a `robots.txt` file to disallow crawling by popular Ai bots.

### Related Issue
Fixes #9

### CODE REVIEW

**Review by yaralahruthik — APPROVED** [review]
This is good and should work in the majority of the cases.

But I am creating another issue to update the documentation to handle this at a traffic level with some common providers like Cloudflare, Vercel etc.,

**Review by yaralahruthik — CHANGES_REQUESTED** [review]
The location of the file is wrong. It should be inside the public folder.

**Comment by NitanJana** [comment]
Also, do you think disallowing all bots upfront and then allowing specific bots would be a better approach in this scenario?

**Comment by yaralahruthik** [comment]
@NitanJana disallowing bots means everything else apart from those bots are allowed. So, we do not have to worry about allowing something explicitly.

**Comment by NitanJana** [comment]
I should clarify. I meant to say, is the following is a better approach? 

Screenshot 2024-09-27 210124

My reasoning would be the exhaustive number of crawlers we want to block.

**Comment by yaralahruthik** [comment]
I'm actually not sure but I believe being explicit about what we are blocking is better. As there are many crawlers that help with visibility and we'd have no idea of them to allow here.

Go ahead with the initial approach of blocking those AI bots specifically.

**Review by yaralahruthik — APPROVED** [review]

**Pull request merged**
