### PR TITLE
feat: dynamically render nav links based on content availibility

### LINKED ISSUE #8: Hide Blog or Learning Pages When No Content Exists
**Is your feature request related to a problem? Please describe.**
I find it frustrating when navigating through the site and landing on a blog or learning page with no content. It results in unnecessary clicks and creates a poor user experience, especially when it gives the impression that something might be there.

**Describe the solution you'd like**
I would like to see the blog and learning sections automatically hidden or not displayed in the navigation menu when they have no content. This would streamline the user experience by only showing pages that have actual information or posts, preventing users from encountering empty sections.

**Describe alternatives you've considered**
One alternative solution could be to display a friendly placeholder message on those pages stating that content is coming soon. However, this still requires users to visit the page, so hiding the empty pages altogether seems like a more efficient approach.

**Additional context**
Implementing this feature could involve checking if the content count for blog or learning posts is zero before rendering the sections in the UI or navigation menu.

### PR DESCRIPTION
**Pull request by NitanJana**
## Summary

This PR closes #8 by conditionally rendering the Blog and Learnings links in the navigation menu based on content availability.

## Changes Made

- Updated the navigation component to check for the length of blog posts and learnings before rendering the corresponding links.

### CODE REVIEW

**Comment by yaralahruthik** [comment]
@NitanJana this would handle the visual part. But the blog and learning page would still generate no content, right? If yes, can we do something about it?

Even these routes should not generate in that case `/blog` and `/learnings`

**Review by yaralahruthik — CHANGES_REQUESTED** [review]
@NitanJana this would handle the visual part. But the blog and learning pages would still generate, right? If yes, can we do something about it?

Even these routes should not generate in that case /blog and /learnings

**Comment by NitanJana** [comment]
I am still stuck on the
> Even these routes should not generate in that case /blog and /learnings

part. I tried tweaking getStaticPaths for this to prevent generating the route at build time if no content is available.

Alternative, sending null response with 404 status code will show not found page but the route will still generate at build time.

**Comment by yaralahruthik** [comment]
@NitanJana you are right. There seems to be no way to not generate a static page from within the page file.

The user had to delete the entire `blog` or `learnings` folder so as not to generate the page. I think we can solve this with documentation in the `README` to tell the user the same. Let me create a new issue for this!

Thanks

**Pull request closed without merging**
